FROM sshforward-build as builder

ADD https://github.com/coord-e/magicpak/releases/latest/download/magicpak-x86_64-unknown-linux-musl /usr/bin/magicpak
RUN chmod +x /usr/bin/magicpak

RUN mkdir -p /app
WORKDIR /app
COPY ./*.c ./*.h Makefile ./
RUN make

RUN /usr/bin/magicpak -v /app/sshforward /bundle

FROM busybox
COPY --from=builder /bundle /.
RUN mkdir -p /key
WORKDIR /key
EXPOSE 3000
ENTRYPOINT ["/app/sshforward"]
