FROM sshforward-dev as builder
RUN mkdir -p /app
WORKDIR /app
COPY . ./
RUN make

FROM debian:buster-slim
RUN apt-get update && apt-get install -y libssh-4
RUN mkdir -p /app
RUN mkdir -p /key
WORKDIR /key
COPY --from=builder /app/sshforward .
EXPOSE 3000
ENTRYPOINT ["/app/sshforward"]